coverage:
  status:
    project:
      default:
        # default
        target: auto
        threshold: 2%
        paths:
          - "fastapi-prophet/app"

ignore:
  - "fastapi-prophet/tests/conftest.py"
