version: '3.8'

services:

  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT:dev
      - TESTING:0
      - DATABASE_URL=postgresql://prophet_fastapi:hello_fastapi@prophet-db:5432/prophet_dev
      - DATABASE_TEST_URL=postgresql://prophet_fastapi:hello_fastapi@prophet-db:5432/prophet_test
    depends_on:
      - prophet-db

  prophet-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=prophet_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
