name: Continuous Integration and Delivery

on:
  push:
    branches: [master]

env:
  IMAGE: docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/web-prophet

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Build and Push to Github Packages
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./project/Dockerfile.prod
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${GITHUB_REPOSITORY}
          tag_with_ref: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  test:
    name: Test Docker Image
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull images
        run: |
          docker pull ${{ env.IMAGE }}-builder:latest || true
          docker pull ${{ env.IMAGE }}-final:latest || true
      - name: Build images
        run: |
          docker build \
            --target builder \
            --cache-from ${{ env.IMAGE }}-builder:latest \
            --tag ${{ env.IMAGE }}-builder:latest \
            --file ./project/Dockerfile.prod \
            "./project"
          docker build \
            --cache-from ${{ env.IMAGE }}-final:latest \
            --tag ${{ env.IMAGE }}-final:latest \
            --file ./project/Dockerfile.prod \
            "./project"
      - name: Run container
        run: |
          docker run \
            -d \
            --name prophet \
            -e PORT=8765 \
            -e ENVIRONMENT=dev \
            -e DATABASE_TEST_URL=sqlite:///sqlite.db \
            -p 5003:8765 \
            ${{ env.IMAGE }}-final:latest
      - name: Install requirements
        run: docker exec prophet pip install -r project/requirements-dev.in
      - name: Pytest
        run: docker exec prophet pytest . -p no:warnings -vv
      - name: Flake8
        run: docker exec prophet python -m flake8 .
      - name: Black
        run: docker exec prophet python -m black . --check
      - name: isort
        run: docker exec prophet python -m isort . --check-only
